/**
 * @file command_dict.h
 * @author PSG_TI_TEAM
 * @brief Command dictionary structures for the UART parser.
 *
 * @details
 * This file defines the metadata structures used by the parsing engine 
 * to map incoming ASCII string commands to their respective hardware opcodes 
 * and memory data types.
 */

#ifndef COMMAND_DICT_H
#define COMMAND_DICT_H

#include "xil_types.h"

/**
 * @brief Allowed data types for parsed command arguments.
 * * @details Used by the parser to determine how many bytes to allocate 
 * in the AXI `HW_OPERAND_BASE` memory region for a given argument.
 */
typedef enum {
    ARG_NONE = 0,    /**< No argument / End of argument list */
    ARG_U8,          /**< 8-bit unsigned integer (1 byte) */
    ARG_U16,         /**< 16-bit unsigned integer (2 bytes) */
    ARG_U32,         /**< 32-bit unsigned integer (4 bytes) */
    ARG_ARRAY_U8     /**< Variable-length array of 8-bit integers (Burst data) */
} arg_type_t;

/** @brief The maximum number of arguments a single API command can accept */
#define MAX_ARGS 5

/**
 * @brief Dictionary entry mapping a string command to its physical execution profile.
 */
typedef struct {
    const char *cmd_string;            /**< The exact string expected from UART (e.g., "spiRawWrite") */
    uint8_t opcode;                    /**< The mapped AXI hardware execution code */
    uint8_t min_args;                  /**< The minimum number of parsed arguments required for execution */
    arg_type_t arg_format[MAX_ARGS];   /**< Array defining the byte-size type for each positional argument */
} command_meta_t;

/* --- Externally Linked Auto-Generated Data --- */

/** @brief The master lookup table generated by the Python automation script */
extern const command_meta_t cmd_dict[];

/** @brief The total number of registered commands in the dictionary */
extern const int DICT_SIZE;

#endif // COMMAND_DICT_H
