/**
 * @file axi_regs.h
 * @author PSG_TI_TEAM
 * @brief Physical AXI memory-mapped register definitions.
 *
 * @details
 * This file defines the hardware-software interface. It maps physical 
 * FPGA AXI Lite register offsets into usable C pointers and macros.
 * * --- Physical Memory Map ---
 * Offset 0x00 - 0x1F : Command Operands (32 Bytes)
 * Offset 0x20        : Opcode Register (1 Byte)
 * Offset 0x21        : Command/Handshake Register (1 Byte)
 * Offset 0x22 - 0x23 : Status/Return Code Register (2 Bytes)
 * Offset 0x24 - 0x63 : Execution Results (64 Bytes)
 */

#ifndef AXI_REGS_H
#define AXI_REGS_H

#include "xparameters.h"
#include "xil_types.h"
#include "xil_io.h"

/** @brief Base address of the custom AXI IP core generated by Vivado */
#define REG_BASE_ADDR  XPAR_REG_32IP_0_SREG_AXI_BASEADDR

/* =========================================================================
 * DATA BUFFERS (Shared Memory Space)
 * ========================================================================= */

/** @brief Pointer to the 32-byte block where parser packs function arguments */
#define HW_OPERAND_BASE ((volatile u8 *)(REG_BASE_ADDR + 0x00)) 

/** @brief Pointer to the 64-byte block where hardware driver writes return data */
#define HW_RESULT_BASE  ((volatile u8 *)(REG_BASE_ADDR + 0x24)) 

/* =========================================================================
 * CONTROL & STATUS REGISTERS
 * ========================================================================= */

/** @brief Offset for the mapped execution opcode */
#define REG_OPCODE      0x20 

/** @brief Offset for the 3-state handshake lock (0=Idle, 1=Trigger, 2=Busy) */
#define REG_COMMAND     0x21 

/** @brief Offset for the hardware return code (Pass/Fail) */
#define REG_STATUS      0x22 

/* =========================================================================
 * HARDWARE ACCESS MACROS
 * ========================================================================= */

#define WRITE_OPCODE(val)  Xil_Out8(REG_BASE_ADDR + REG_OPCODE, (u8)(val))
#define READ_OPCODE()      Xil_In8(REG_BASE_ADDR + REG_OPCODE)

#define WRITE_CMD(val)     Xil_Out8(REG_BASE_ADDR + REG_COMMAND, (u8)(val))
#define READ_CMD()         Xil_In8(REG_BASE_ADDR + REG_COMMAND)

#define WRITE_STATUS(val)  Xil_Out16(REG_BASE_ADDR + REG_STATUS, (u16)(val))
#define READ_STATUS()      Xil_In16(REG_BASE_ADDR + REG_STATUS)

#endif // AXI_REGS_H
