# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0.xci
# IP: The module: 'hw_block_ddr_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_block_ddr_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_block_ddr_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0.xci
# IP: The module: 'hw_block_ddr_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_block_ddr_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vlsiuser/phase2/week12/week12.srcs/sources_1/bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_block_ddr_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
