# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw_block_ddr/hw_block_ddr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr || ORIG_REF_NAME==hw_block_ddr} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_microblaze_0_0/hw_block_ddr_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_microblaze_0_0 || ORIG_REF_NAME==hw_block_ddr_microblaze_0_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_dlmb_v10_0/hw_block_ddr_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_dlmb_v10_0 || ORIG_REF_NAME==hw_block_ddr_dlmb_v10_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_ilmb_v10_0/hw_block_ddr_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_ilmb_v10_0 || ORIG_REF_NAME==hw_block_ddr_ilmb_v10_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_dlmb_bram_if_cntlr_0/hw_block_ddr_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw_block_ddr_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_ilmb_bram_if_cntlr_0/hw_block_ddr_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hw_block_ddr_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_lmb_bram_0/hw_block_ddr_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_lmb_bram_0 || ORIG_REF_NAME==hw_block_ddr_lmb_bram_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_xbar_0/hw_block_ddr_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_xbar_0 || ORIG_REF_NAME==hw_block_ddr_xbar_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_us_0/hw_block_ddr_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_us_0 || ORIG_REF_NAME==hw_block_ddr_auto_us_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_0/hw_block_ddr_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_ds_0 || ORIG_REF_NAME==hw_block_ddr_auto_ds_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_cc_0/hw_block_ddr_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_cc_0 || ORIG_REF_NAME==hw_block_ddr_auto_cc_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_pc_0/hw_block_ddr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_pc_0 || ORIG_REF_NAME==hw_block_ddr_auto_pc_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_1/hw_block_ddr_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_ds_1 || ORIG_REF_NAME==hw_block_ddr_auto_ds_1} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_auto_ds_2/hw_block_ddr_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_auto_ds_2 || ORIG_REF_NAME==hw_block_ddr_auto_ds_2} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_microblaze_0_axi_periph_0/hw_block_ddr_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hw_block_ddr_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_microblaze_0_axi_intc_0/hw_block_ddr_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hw_block_ddr_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_microblaze_0_xlconcat_0/hw_block_ddr_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_microblaze_0_xlconcat_0 || ORIG_REF_NAME==hw_block_ddr_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_mdm_1_0/hw_block_ddr_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_mdm_1_0 || ORIG_REF_NAME==hw_block_ddr_mdm_1_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_clk_wiz_1_0/hw_block_ddr_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_clk_wiz_1_0 || ORIG_REF_NAME==hw_block_ddr_clk_wiz_1_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_rst_clk_wiz_1_100M_0/hw_block_ddr_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==hw_block_ddr_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_mig_7series_0_0/hw_block_ddr_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_mig_7series_0_0 || ORIG_REF_NAME==hw_block_ddr_mig_7series_0_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_reg_32ip_0_1/hw_block_ddr_reg_32ip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_reg_32ip_0_1 || ORIG_REF_NAME==hw_block_ddr_reg_32ip_0_1} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_axi_uartlite_0_0/hw_block_ddr_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_axi_uartlite_0_0 || ORIG_REF_NAME==hw_block_ddr_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hw_block_ddr/ip/hw_block_ddr_rst_mig_7series_0_81M_0/hw_block_ddr_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_block_ddr_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==hw_block_ddr_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: bd/hw_block_ddr/hw_block_ddr_ooc.xdc
